version: '3'

services:
  vaadin-app:
    image: your-vaadin-app-image:latest  # Replace with your Vaadin Docker image
    ports:
      - "8080:8080"  # Map Vaadin app to localhost:8080

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount the configuration file
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"  # Prometheus web UI will be available at localhost:9090
    depends_on:
      - vaadin-app
